//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int id { get; set; }
        public bool critical { get; set; }
        public int reporterId { get; set; }
        public System.DateTime reportDate { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public bool service { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> contractorId { get; set; }
        public string comments { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Person Person { get; set; }
    }
}
