//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Lends = new HashSet<Lend>();
        }
    
        public int id { get; set; }
        public int carId { get; set; }
        public System.DateTime reservationDate { get; set; }
        public System.DateTime lendDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<int> lendId { get; set; }
        public bool ended { get; set; }
        public Nullable<bool> @private { get; set; }
        public int personId { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lend> Lends { get; set; }
        public virtual Lend Lend { get; set; }
        public virtual Person Person { get; set; }
    }
}
